### ISSUE TITLE
Build for IOS?

### ISSUE THREAD

**Issue by Krosh** [MilosLukic/Godot-Navigation-Lite#9]
Hello, i want to help you with build for Mac OS. What should i do?

**Comment by MilosLukic** [comment]
Hello, I think that the newest PR added Mac support.

https://github.com/MilosLukic/Godot-Navigation-Lite/pull/8

But if you manage to fix a bug or add a new feature, you could build it by following this tutorial: 

https://docs.godotengine.org/en/stable/tutorials/plugins/gdnative/gdnative-cpp-example.html
